//
//  HomeInteractor.swift
//  CountriesApp
//
//  Created by Daniel Silva on 28/03/2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HomeBusinessLogic {
    func searchCountry(request: Home.Search.Request)
}

protocol HomeDataStore {
    // Variables to store data to be passed between scenes
}

class HomeInteractor: HomeBusinessLogic, HomeDataStore {
    var presenter: HomePresentationLogic?
    var worker: HomeWorker?

    func searchCountry(request: Home.Search.Request) {
        worker = HomeWorker()
        worker?.fetchCountryInfo(countryName: request.countryName) { [weak self] result in
            switch result {
            case .success(let country):
                let response = Home.Search.Response(result: .success(country))
                self?.presenter?.presentCountrySearchResult(response: response)
            case .failure(let error):
                self?.presenter?.presentError(error: error)
            }
        }
    }
}
