//
//  HomeModels.swift
//  CountriesApp
//
//  Created by Daniel Silva on 28/03/2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Home {
    enum Search {
        struct Request {
            let countryName: String
        }

        struct Response {
            let result: Result<Country, Error>
        }

        struct ViewModel {
            let isError: Bool
            let errorMessage: String?
        }
    }
}

struct Country: Decodable {
    let cca2: String
    let languages: [String: String]
    let currencies: [String: Currency]
    let flags: [String: String]

    struct Currency: Decodable {
        let name: String
        let symbol: String
    }
}

