//
//  ChangeCurrencyPresenter.swift
//  CountriesApp
//
//  Created by Daniel Silva on 05/04/2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ChangeCurrencyPresentationLogic {
    func presentSomething(response: ChangeCurrency.Country.Response)
}

class ChangeCurrencyPresenter: ChangeCurrencyPresentationLogic {
    weak var viewController: ChangeCurrencyDisplayLogic?

    // MARK: Do something

    func presentSomething(response: ChangeCurrency.Country.Response) {
        let countriesName : [String] = response.countries.map { country in
            country.name.common
        }
        let viewModel = ChangeCurrency.Country.ViewModel(countryName: countriesName)

        viewController?.displaySomething(viewModel: viewModel)
    }
}
