//
//  ChangeCurrencyPresenter.swift
//  CountriesApp
//
//  Created by Daniel Silva on 05/04/2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ChangeCurrencyPresentationLogic
{
  func presentSomething(response: ChangeCurrency.Something.Response)
}

class ChangeCurrencyPresenter: ChangeCurrencyPresentationLogic
{
  weak var viewController: ChangeCurrencyDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: ChangeCurrency.Something.Response)
  {
    let viewModel = ChangeCurrency.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
