//
//  ChangeCurrencyInteractor.swift
//  CountriesApp
//
//  Created by Daniel Silva on 05/04/2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ChangeCurrencyBusinessLogic
{
  func doSomething(request: ChangeCurrency.Something.Request)
}

protocol ChangeCurrencyDataStore
{
  //var name: String { get set }
}

class ChangeCurrencyInteractor: ChangeCurrencyBusinessLogic, ChangeCurrencyDataStore
{
  var presenter: ChangeCurrencyPresentationLogic?
  var worker: ChangeCurrencyWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: ChangeCurrency.Something.Request)
  {
    worker = ChangeCurrencyWorker()
    worker?.doSomeWork()
    
    let response = ChangeCurrency.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
