//
//  CountryDetailPresenter.swift
//  CountriesApp
//
//  Created by Daniel Silva on 29/03/2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CountryDetailPresentationLogic
{
  func presentSomething(response: CountryDetail.Something.Response)
}

class CountryDetailPresenter: CountryDetailPresentationLogic
{
  weak var viewController: CountryDetailDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: CountryDetail.Something.Response)
  {
    let viewModel = CountryDetail.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
