//
//  CountryDetailInteractor.swift
//  CountriesApp
//
//  Created by Daniel Silva on 29/03/2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CountryDetailBusinessLogic {
    func doSomething(request: CountryDetail.Something.Request)
}

protocol CountryDetailDataStore {
    var country: Country? { get set }
}

class CountryDetailInteractor: CountryDetailBusinessLogic, CountryDetailDataStore {
    var presenter: CountryDetailPresentationLogic?
    var worker: CountryDetailWorker?
    var country: Country?

    // MARK: Do something

    func doSomething(request: CountryDetail.Something.Request) {
        let response = CountryDetail.Something.Response(country: request.country)
        presenter?.presentCountrySearchResult(response: response)
    }
}
