//
//  CountryDetailInteractor.swift
//  CountriesApp
//
//  Created by Daniel Silva on 29/03/2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CountryDetailBusinessLogic {
    func getCountryData(request: CountryDetail.CountryDetail.Request)
}

protocol CountryDetailDataStore {
    var country: Country? { get set }
}

class CountryDetailInteractor: CountryDetailBusinessLogic, CountryDetailDataStore {
    var presenter: CountryDetailPresentationLogic?
    var worker: CountryDetailWorker?
    var country: Country?

    // MARK: Do something

    func getCountryData(request: CountryDetail.CountryDetail.Request) {
        worker = CountryDetailWorker()
        guard let flagString = request.country.flags["png"] else { return }
        worker?.loadCountryImage(from: flagString, completion: { [weak self] image in
            if let image = image {
                let response = CountryDetail.CountryDetail.Response(country: request.country, flag: image)
                self?.presenter?.presentCountrySearchResult(response: response)
            } else {
                let response = CountryDetail.CountryDetail.Response(country: request.country, flag: nil)
                self?.presenter?.presentCountrySearchResult(response: response)
            }
        })
    }
}
