//
//  CountryDetailInteractor.swift
//  CountriesApp
//
//  Created by Daniel Silva on 29/03/2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CountryDetailBusinessLogic
{
  func doSomething(request: CountryDetail.Something.Request)
}

protocol CountryDetailDataStore
{
  //var name: String { get set }
}

class CountryDetailInteractor: CountryDetailBusinessLogic, CountryDetailDataStore
{
  var presenter: CountryDetailPresentationLogic?
  var worker: CountryDetailWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: CountryDetail.Something.Request)
  {
    worker = CountryDetailWorker()
    worker?.doSomeWork()
    
    let response = CountryDetail.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
